baseURL: "https://www.jinyeran.com" 
title: Welcome to Jinye's homepage
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: CV
          url: cv.pdf
          weight: 1
        - name: Research
          url: research/
          weight: 2
        - name: Projects
          url: projects/
          weight: 3
        - name: Publications
          url: publications/
          weight: 4

params:
    description: "" # 需要填
    author: Jinye Ran
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Jinye Ran
          subtitle: "Hello! This is Jinye Ran. I have earned my Master’s degree in Computer Science and Technology from Southwest University and am applying to a PhD program. My research interests lie in the general area of machine learning, particularly in transfer learning and disentangled representation. I currently focus on applications in the continuous and unstructured data setting such as computer vision (e.g., feature disentanglement and domain adaptation) and healthcare (e.g., how to improve label efficiency and model interpretability).

<br><br>
Looking ahead, I aim to develop machine learning techniques that are more adaptable, efficient, and interpretable, applying my research to tackle real-world challenges in healthcare."
          imageUrl: "picture.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Jinye Ran
          buttons:
            - name: CV
              url: cv.pdf
            - name: Research
              url: research
            - name: Projects
              url: projects/
            - name: Publications
              url: publications/

    socialIcons:
        - name: Email
          url: mailto:jinyeran47@gmail.com
        - name: Linkedin
          url: https://www.linkedin.com/in/jinye-r-750b8632a/
        - name: GoogleScholar
          url: https://scholar.google.com/citations?&user=I0TRLhUAAAAJ
        - name: GitHub
          url: https://github.com/JinyeRAN



    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Jinye Ran"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2